In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

In [2]:
df=pd.read_excel("/home/user/Desktop/env2/VAR/Rates_value_adjusted.xlsx")
df.tail()

,Date,LIBOR ON,LIBOR 1W,LIBOR 1M,LIBOR 2M,LIBOR 3M,LIBOR 6M,LIBOR 12M,SOFR Rate,30-Day Average SOFR,90-Day Average SOFR,180-Day Average SOFR,SONIA DAILY RATE,TIIE DAILY AVG RATES,TIIE 28-Day Avg Rates,TIIE 91-Day Avg Rates,TIIE 26-Weeks Avg Rates
1339,31.03.2021,0.07288,0.08188,0.10850,0.13500,0.20250,0.20288,0.28150,0.01,0.01467,0.04167,0.06034,0.08998,4.20,4.2875,4.248,4.3091
1340,01.04.2021,0.07475,0.08488,0.11038,0.13525,0.19975,0.20125,0.28050,0.01,0.01433,0.04100,0.06034,0.08112,NaN,NaN,NaN,NaN
1341,05.04.2021,0.07475,0.08488,0.11038,0.13525,0.19975,0.20125,0.28050,0.01,0.01167,0.03800,0.06034,NaN,4.06,4.2875,4.249,NaN
1342,06.04.2021,0.07788,0.08613,0.11013,0.14413,0.19738,0.20100,0.28625,0.01,0.01133,0.03689,0.06034,0.08545,4.03,4.2880,4.251,NaN
1343,07.04.2021,0.07625,0.08588,0.11250,0.14563,0.19363,0.21000,0.28525,0.01,0.01100,0.03589,0.06034,0.08367,4.01,4.2885,4.250,NaN

In [3]:
df.fillna(method='ffill',inplace=True)
df.index=df['Date']
df.isnull().sum()

Date                       0
LIBOR ON                   0
LIBOR 1W                   0
LIBOR 1M                   0
LIBOR 2M                   0
LIBOR 3M                   0
LIBOR 6M                   0
LIBOR 12M                  0
SOFR Rate                  0
30-Day Average SOFR        0
90-Day Average SOFR        0
180-Day Average SOFR       0
SONIA DAILY RATE           0
TIIE DAILY AVG RATES       0
TIIE 28-Day Avg Rates      0
TIIE 91-Day Avg Rates      0
TIIE 26-Weeks Avg Rates    0
dtype: int64

In [4]:
df.describe().to_csv('summary.xlsx')