In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

In [2]:
df=pd.read_excel("/home/user/Desktop/env2/VAR/Rates with SOFR.xlsx")
df.tail()

,Date,LIBOR ON,LIBOR 1W,LIBOR 1M,LIBOR 2M,LIBOR 3M,LIBOR 6M,LIBOR 12M,SOFR Rate,30-Day Average SOFR,90-Day Average SOFR,180-Day Average SOFR,SONIA DAILY RATE,TIIE DAILY AVG RATES,TIIE 28-Day Avg Rates,TIIE 91-Day Avg Rates,TIIE 26-Weeks Avg Rates
771,31.03.2021,0.07288,0.08188,0.10850,0.13500,0.20250,0.20288,0.28150,0.01,0.01467,0.04167,0.06034,0.0475,4.20,4.2875,4.248,4.3091
772,01.04.2021,0.07475,0.08488,0.11038,0.13525,0.19975,0.20125,0.28050,0.01,0.01433,0.04100,0.06034,0.0475,NaN,NaN,NaN,NaN
773,05.04.2021,0.07475,0.08488,0.11038,0.13525,0.19975,0.20125,0.28050,0.01,0.01167,0.03800,0.06034,0.0482,4.06,4.2875,4.249,NaN
774,06.04.2021,0.07788,0.08613,0.11013,0.14413,0.19738,0.20100,0.28625,0.01,0.01133,0.03689,0.06034,0.0483,4.03,4.2880,4.251,NaN
775,07.04.2021,0.07625,0.08588,0.11250,0.14563,0.19363,0.21000,0.28525,0.01,0.01100,0.03589,0.06034,0.0483,4.01,4.2885,4.250,NaN

In [3]:
df.fillna(method='ffill',inplace=True)
df.index=df['Date']
df.isnull().sum()

Date                       0
LIBOR ON                   0
LIBOR 1W                   0
LIBOR 1M                   0
LIBOR 2M                   0
LIBOR 3M                   0
LIBOR 6M                   0
LIBOR 12M                  0
SOFR Rate                  0
30-Day Average SOFR        0
90-Day Average SOFR        0
180-Day Average SOFR       0
SONIA DAILY RATE           0
TIIE DAILY AVG RATES       0
TIIE 28-Day Avg Rates      0
TIIE 91-Day Avg Rates      0
TIIE 26-Weeks Avg Rates    3
dtype: int64

In [4]:
df.describe()

,LIBOR ON,LIBOR 1W,LIBOR 1M,LIBOR 2M,LIBOR 3M,LIBOR 6M,LIBOR 12M,SOFR Rate,30-Day Average SOFR,90-Day Average SOFR,180-Day Average SOFR,SONIA DAILY RATE,TIIE DAILY AVG RATES,TIIE 28-Day Avg Rates,TIIE 91-Day Avg Rates,TIIE 26-Weeks Avg Rates
count,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,776.000000,773.000000
mean,1.324670,1.365177,1.452638,1.530417,1.611726,1.667263,1.785203,1.349137,1.374250,1.425054,1.468279,0.447699,6.808698,7.048877,7.030343,6.973452
std,0.952745,0.948051,0.951862,0.960624,0.984977,1.006585,1.050381,0.993217,0.968995,0.933975,0.894766,0.299950,1.564149,1.572727,1.586350,1.632742
min,0.050750,0.079130,0.103000,0.133630,0.175250,0.189500,0.275880,0.010000,0.011000,0.035890,0.060340,0.039400,3.920000,4.281200,4.222500,4.195000
25%,0.083000,0.108687,0.173720,0.233750,0.276345,0.361097,0.502285,0.090000,0.087000,0.092147,0.420430,0.060300,5.077500,5.255900,5.225275,5.050400
50%,1.704380,1.748440,1.895565,2.003255,2.049755,1.986565,1.978440,1.725000,1.741680,1.778860,1.864320,0.701000,7.580000,7.850550,7.860200,7.687500
75%,2.175160,2.212582,2.281910,2.322845,2.363750,2.530500,2.772267,2.200000,2.220325,2.249073,2.208190,0.708900,8.050000,8.278875,8.318200,8.335500
max,2.402750,2.430880,2.522380,2.652880,2.823750,2.907880,3.144130,5.250000,2.502760,2.450980,2.453260,0.712700,8.500000,8.600000,8.637500,8.665000